//! The dsql grammar: generated logos lexer, generated lelwel parser, and
//! the parse entry point producing a lossless CST.
//!
//! `dsql.llw` is the single source of truth for language constructs: the
//! generated [`parser::Rule`] enum drives all dispatch, and the [`lexer`]
//! is generated from the grammar's token declarations by the vendored
//! lelwel (literal spellings from the grammar, regex patterns from
//! build.rs). Nothing hand-mirrors the grammar.

/// Generated by `lelwel::build_lexer` from `dsql.llw`.
pub mod lexer {
    include!(concat!(env!("OUT_DIR"), "/lexer.rs"));
}
#[expect(
    clippy::single_match,
    reason = "lelwel emits a one-arm CST cleanup match when error nodes have delete hooks"
)]
pub mod parser;

use parser::{Cst, Diagnostic, Parser};

/// Parses dsql source text into a lossless CST plus parse diagnostics.
///
/// The CST retains all trivia (whitespace, comments) and error nodes, so it
/// is suitable for formatting and editor services as well as lowering.
pub fn parse(source: &str) -> (Cst<'_>, Vec<Diagnostic>) {
    let mut diagnostics = Vec::new();
    let cst = Parser::new(source, &mut diagnostics).parse(&mut diagnostics);
    (cst, diagnostics)
}
