[workspace]
resolver = "3"
members = ["crates/*"]
exclude = ["vendor/lelwel", "vendor/logos"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
dsql-core = { path = "crates/dsql-core" }
dsql-project = { path = "crates/dsql-project" }

bowl = { git = "https://github.com/Nohac/porridge", rev = "e03d8ff59e3bc2c55dc0d3af5de1bcedaeb577e4" }
lelwel = { path = "vendor/lelwel" }
logos = { path = "vendor/logos" }

clap = { version = "4.5", features = ["derive"] }
codespan-reporting = "0.13"
facet = "0.50.0-rc.1"
facet-toml = "0.50.0-rc.1"
facet-yaml = "0.50.0-rc.1"
futures = "0.3"
insta = "1.48"
ropey = "2.0.0-beta.1"
sea-query = { version = "1.0.1", default-features = false, features = ["backend-postgres"] }
sqlformat = "0.5"
strum = { version = "0.28", features = ["derive"] }
thiserror = "2"
