[workspace]
resolver = "2"
members = [
    "crates/*",
    "tests",
]

[workspace.dependencies]
dsql-cli = { path = "crates/cli" }
dsql-core = { path = "crates/core" }
dsql-embedding = { path = "crates/embedding" }
dsql-frontend = { path = "crates/frontend" }
dsql-generate = { path = "crates/generate" }
dsql-introspection = { path = "crates/introspection" }
dsql-lsp = { path = "crates/lsp" }
dsql-metadata = { path = "crates/metadata" }
dsql-project = { path = "crates/project" }

camino = "1"
clap = "4"
codespan-reporting = "0.13"
dashmap = "6.1"
facet = "0.46.2"
facet-json = "0.46.0"
facet-jsonschema = "0.46.0"
facet-toml = "0.46.0"
facet-typescript = "0.46.0"
facet-value = "0.46.0"
facet-yaml = "0.46.0"
glob = "0.3"
indexmap = "2"
insta = "1"
lasso = "0.7"
lelwel = { path = "/home/jonas/Development/Rust/lelwel" }
logos = "0.16"
miette = "7"
picante = { version = "2.0.0", default-features = false }
regex = "1"
ropey = "2.0.0-beta.1"
sea-query = { version = "1.0.0-rc.34", default-features = false }
smallvec = "1"
sqlformat = "0.5"
sqlx = { version = "0.8", default-features = false }
strum = "0.27"
tempfile = "3"
thiserror = "2"
tokio = "1"
tower-lsp-server = "0.22"
tracing = "0.1"
tracing-subscriber = "0.3"
