[package]
name = "dsql-frontend"
version = "0.1.0"
edition = "2024"

[dependencies]
dashmap = { workspace = true }
dsql-core = { workspace = true }
dsql-embedding = { workspace = true }
dsql-project = { workspace = true }
facet = { workspace = true }
picante = { workspace = true, features = ["macros"] }
ropey = { workspace = true, features = ["metric_utf16"] }
strum = { workspace = true, features = ["derive"] }
tracing = { workspace = true }
