export const KEYWORDS = Object.freeze({
  query: "query",
  fragment: "fragment",
  filter: "filter",
  condition: "condition",
  context: "context",
  on: "on",
  selected: "selected",
  indexed: "indexed",
  selectedIndexed: "selected_indexed",
  searchable: "searchable",
  apply: "apply",
  when: "when",
  field: "field",
  where: "where",
  order: "order",
  by: "by",
  limit: "limit",
  offset: "offset",
  asc: "asc",
  desc: "desc",
  true: "true",
  false: "false",
  null: "null",
  like: "like",
  and: "and",
  or: "or",
  not: "not",
  in: "in",
  is: "is",
  exists: "exists",
});

export const SYMBOLS = Object.freeze({
  leftBrace: "{",
  rightBrace: "}",
  leftParenthesis: "(",
  rightParenthesis: ")",
  leftBracket: "[",
  rightBracket: "]",
  qualified: "::",
  leftArrow: "<-",
  arrow: "->",
  colon: ":",
  at: "@",
  comma: ",",
  pipe: "|",
  ellipsis: "...",
  parent: "..",
  current: ".",
  root: "~",
  topLevel: "%",
  structured: "$",
  optional: "?",
  assign: "=",
  equal: "==",
  notEqual: "!=",
  greater: ">",
  greaterEqual: ">=",
  less: "<",
  lessEqual: "<=",
});

export const LITERALS = Object.freeze([
  ...Object.values(KEYWORDS),
  ...Object.values(SYMBOLS),
].sort());

export const TERMINAL_PATTERNS = Object.freeze({
  Name: "[A-Za-z_][A-Za-z0-9_]*",
  String: '\"([^\"\\\\]|\\\\.)*\"',
  Number: "-?[0-9]+(\\.[0-9]+)?",
  Whitespace: "[ \\t\\r\\n]+",
  Comment: "#[^\\n\\r]*",
});
