[package]
name = "dsql-project"
version = "0.1.0"
edition = "2024"

[dependencies]
dsql-core = { workspace = true }
dsql-embedding = { workspace = true }
facet = { workspace = true }
facet-toml = { workspace = true, features = ["serialize"] }
glob = { workspace = true }
miette = { workspace = true, features = ["fancy"] }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
