// Generated by `dsql project sync`; a copied scaffold replaces this example
// with the consuming project's exact contract.
import { defineDsqlProject } from "@dsql/typescript/renderer";

export const project = defineDsqlProject({
  contractHash: {
    algorithm: "sha256",
    value: "0000000000000000000000000000000000000000000000000000000000000000",
  },
  scopes: {
    ["api"]: { imports: ["shared"] },
    ["frontend"]: { imports: ["shared"] },
    ["shared"]: { imports: [] },
  },
  targets: ["api", "frontend"],
  directives: {},
});
