[package]
name = "dsql-core"
version.workspace = true
edition.workspace = true

[dependencies]
bowl = { workspace = true }
codespan-reporting = { workspace = true }
logos = { workspace = true }
ropey = { workspace = true }

[build-dependencies]
lelwel = { workspace = true }

[dev-dependencies]
futures = { workspace = true }
insta = { workspace = true }
