[package]
name = "dsql-generate"
version = "0.1.0"
edition = "2024"

[features]
default = ["fs", "process"]
fs = ["tokio/fs"]
process = ["tokio/process"]

[dependencies]
dsql-core = { workspace = true }
dsql-embedding = { workspace = true }
dsql-metadata = { workspace = true }
dsql-project = { workspace = true }
facet = { workspace = true }
facet-json = { workspace = true }
glob = { workspace = true }
miette = { workspace = true, features = ["fancy"] }
tokio = { workspace = true }
