[package]
name = "dsql-project"
version.workspace = true
edition.workspace = true

[dependencies]
bowl = { workspace = true }
dsql-core = { workspace = true }
facet = { workspace = true }
facet-toml = { workspace = true }
glob = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
futures = { workspace = true }
