[package]
name = "dsql-core"
version = "0.1.0"
edition = "2024"

[dependencies]
camino = { workspace = true }
codespan-reporting = { workspace = true }
enum_dispatch = { workspace = true }
facet = { workspace = true }
facet-yaml = { workspace = true }
indexmap = { workspace = true }
lasso = { workspace = true }
logos = { workspace = true }
miette = { workspace = true }
ropey = { workspace = true, features = ["metric_utf16"] }
sea-query = { workspace = true, features = ["backend-postgres"] }
smallvec = { workspace = true }
sqlformat = { workspace = true }
strum = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
tracing = { workspace = true }

[build-dependencies]
lelwel = { workspace = true }
