[package]
name = "dsql-daemon"
version.workspace = true
edition.workspace = true

[dependencies]
bowl = { workspace = true }
dsql-core = { workspace = true }
dsql-generate = { workspace = true }
dsql-metadata = { workspace = true }
dsql-project = { workspace = true }
facet = { workspace = true }
facet-json = { workspace = true }
facet-value = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
fd-lock = { workspace = true }
insta = { workspace = true }
